services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-eve}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-eve}
      POSTGRES_USER: ${POSTGRES_USER:-eve}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - 55432:5432
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
